package com.travel.system.model;
// Generated 2019-1-25 21:47:24 by Hibernate Tools 5.0.6.Final

import java.util.Date;

/**
 * SysApplication generated by hbm2java
 */
public class SysApplication implements java.io.Serializable {

	private Integer appId;
	private String appCode;
	private String appName;
	private String appDesc;
	private Boolean showInMenu;
	private Integer createUserId;
	private Date createDate;
	private Integer modifyUserId;
	private Date modifyDate;

	public SysApplication() {
	}

	public SysApplication(String appCode, String appName, String appDesc, Boolean showInMenu, Integer createUserId,
			Date createDate, Integer modifyUserId, Date modifyDate) {
		this.appCode = appCode;
		this.appName = appName;
		this.appDesc = appDesc;
		this.showInMenu = showInMenu;
		this.createUserId = createUserId;
		this.createDate = createDate;
		this.modifyUserId = modifyUserId;
		this.modifyDate = modifyDate;
	}

	public Integer getAppId() {
		return this.appId;
	}

	public void setAppId(Integer appId) {
		this.appId = appId;
	}

	public String getAppCode() {
		return this.appCode;
	}

	public void setAppCode(String appCode) {
		this.appCode = appCode;
	}

	public String getAppName() {
		return this.appName;
	}

	public void setAppName(String appName) {
		this.appName = appName;
	}

	public String getAppDesc() {
		return this.appDesc;
	}

	public void setAppDesc(String appDesc) {
		this.appDesc = appDesc;
	}

	public Boolean getShowInMenu() {
		return this.showInMenu;
	}

	public void setShowInMenu(Boolean showInMenu) {
		this.showInMenu = showInMenu;
	}

	public Integer getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Integer getModifyUserId() {
		return this.modifyUserId;
	}

	public void setModifyUserId(Integer modifyUserId) {
		this.modifyUserId = modifyUserId;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

}
